### ISSUE TITLE
Badge pro komponenty dle slozitosti

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1734]
Padak: tu složitost bych tam rád - bavili jsme se v IT o tom, že by nám Hanka
pomohla říct, co je jak složité. Já mám pocitově "nastavím to bez
dokumentace do 1min", "nastavím to s dokumentací do 5 mint", je to "vomrd a
budu na tom seklej". Prostě 1/2/3 hvězdičky...

https://github.com/keboola/kbc-ui/issues/1464#issuecomment-392472406

**Comment by ujovlado** [comment]
Bude treba aby sme sa dohodli, kde budeme info o zlozitosti setupu komponenty drzat a ako sa to bude ukladat. Ci ciselne (1,2,3) alebo slovne (easy, advanced, hard) a pod. No a potom kto by mal povedat, ako lahke je komponenty nastavit? imho to na developerov uplne nechat nemozeme - vsetko by potom bolo asi "easy". Takze len pre adminov?

**Comment by padak** [comment]
Budeme to řešit my a bude to easy / medium / hard.

easy - bez přípravy a znalosti api/systému to nastavíš klikačkou za 2 min
medium - naklikáš to na pohodu, ale musíš zamířit na dokumentaci, jinak to sám nedáš
hard - generic a spol. (typicky elastic ex, mongodb, atd.) - prostě věci co neinvestujeme do UI nebo jsou "by design" složitý

Definujeme to ručně, na základě feedbacku od Hanky a nás + k tomu doufám dost pomůže https://github.com/keboola/internal/issues/13

Dává to tak smysl?

**Comment by ujovlado** [comment]
Jo, dava to zmysel. Mohli by sme teda pridat flag `complexity` (alebo `ease`?) ku komponente a ukladali by sme tam jednu z tych troch hodnot. Alebo to opat spravime cez `uiOptions` tak ako flag `beta`? Zalozim issue na devportal, tam sa to hodi viac.

**Comment by ujovlado** [comment]
Doriesme to tu: https://github.com/keboola/developer-portal/issues/206

Az to bude chodit v responses z API, doriesit to v UI uz bude hracka.

**Comment by jancermak** [comment]
@jancermak pozn. pro me dodat aktualizovanou verzi znaceni - vychazejici z tutoho jen zarovnano na pravou stranu k labelum.

![otagovani-komponent-v7](https://user-images.githubusercontent.com/1826442/43525452-151e57e4-95a2-11e8-8d08-a159957b2566.png)
